name: Deploy Sage Theme to IONOS (SFTP, no keys)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Cache Node
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node-

      - name: Install PHP deps (no-dev)
        run: composer install --no-dev --prefer-dist --no-progress --no-interaction

      - name: Install Node deps
        run: npm ci

      - name: Build production assets
        run: npm run build

      - name: Prepare deploy folder
        run: |
          mkdir -p deploy
          rsync -a \
            --delete \
            --exclude ".git*" \
            --exclude ".github" \
            --exclude "node_modules" \
            --exclude ".env" \
            --exclude "tests" \
            --exclude "vendor/bin" \
            --exclude "*.map" \
            ./ deploy/

      # Upload via SFTP + password (no SSH key)
      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_HOST }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: ./deploy/
          remote_path: ${{ secrets.REMOTE_PATH }}/
          sftp_only: true
          sftpArgs: "-o StrictHostKeyChecking=no"
